version: "3.8"

services:
  web:
    build: .
    container_name: web_service
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/opt/src/staticfiles
      - media_volume:/opt/src/media
    ports:
      - "8000"
    env_file:
      - src/.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_service
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - "5432"
    env_file:
      - src/.env

  nginx:
    build: ./nginx
    container_name: nginx_service
    volumes:
      - static_volume:/opt/src/staticfiles
      - media_volume:/opt/src/media
      - /etc/letsencrypt/live/words-learn-helper.com:/etc/letsencrypt/live/words-learn-helper.com
      - /etc/letsencrypt/live/words-learn-helper.com/privkey.pem:/etc/letsencrypt/live/words-learn-helper.com/privkey.pem
    ports:
      - "80:80" # requests from host on 80, go into 80 of container
      - "443:443"
    depends_on:
      - db

volumes:
  db_volume:
    name: db_data_1
  static_volume:
    name: static_data_1
  media_volume:
    name: media_data_1
